<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;


class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
     public function run(): void
    {
        $products = [
            // 🩷 Kitty Collection
            [
                'name' => 'Monchhichi x Hello Kitty Plush Doll',
                'price' => 700.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty2.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Classic Twin Figurines',
                'price' => 640.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty3.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Red Sparkle Outfit Plush',
                'price' => 670.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty4.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Strawberry Basket Figurine',
                'price' => 620.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty5.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Brown Bear Face Plush',
                'price' => 580.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty6.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty with baby kitty   ',
                'price' => 460.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty7.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty AND Apple figurine ',
                'price' => 430.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty8.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty And Tea Set ',
                'price' => 440.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty9.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Picnic Time ',
                'price' => 490.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty10.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Mimo Figurine',
                'price' => 680.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty11.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Red Dress Figurine',
                'price' => 700.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty12.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Polka Dot Dress Plush',
                'price' => 610.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty13.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Classic Hello Kitty Plush Doll',
                'price' => 580.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty14.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Sakura Pink Plush',
                'price' => 630.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty15.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Black Cat Costume Plush',
                'price' => 650.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty16.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Cozy Brown Outfit Plush',
                'price' => 520.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty17.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Bear Costume Plush',
                'price' => 670.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty18.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Pink Velvet Bow Plush',
                'price' => 590.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty19.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty White Pearl Plush',
                'price' => 620.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty20.png',
                'category_id' => 1,
            ],
            [
                'name' => 'Hello Kitty Paris Pink Dress Plush',
                'price' => 690.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kitty/kitty21.png',
                'category_id' => 1,
            ],

            // 💖 My Melody Collection
            [
                'name' => 'My Melody Birthday Cake Topper Figure',
                'price' => 490.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody2.png',
                'category_id' => 2,
            ],
            [
                'name' => 'My Melody Picnic Day Figurine ',
                'price' => 520.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody3.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Elegant Lolita Figurine ',
                'price' => 480.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody4.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Chocolate Dream Plush Pouch ',
                'price' => 550.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody5.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Gothic Punk Clip ',
                'price' => 420.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody6.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Fluffy Pink Bear Costume Plush ',
                'price' => 590.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody7.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Classic Bow Clip-On ',
                'price' => 400.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody8.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody with Mini Me ',
                'price' => 650.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody9.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Sweet Ride Figurine',
                'price' => 680.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody10.png',
                'category_id' => 2,
            ],
             [
                'name' => 'Classic My Melody Plush ',
                'price' => 490.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody11.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Pink Gingham Beret Plush',
                'price' => 560.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody12.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Sky Blue Bow Prayer Figure ',
                'price' => 430.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody13.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Nurse Uniform Figure ',
                'price' => 540.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody14.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Lollipop Treat Action Figure ',
                'price' => 580.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody15.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Victorian Frill Dress Figure',
                'price' => 610.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody16.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Pastel Easter Bonnet Charm ',
                'price' => 490.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody17.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Blue Dot Dress with Plushie ',
                'price' => 450.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody18.png',
                'category_id' => 2,
            ],
             [
                'name' => 'My Melody Heart Pocket Pink Dress Charm',
                'price' => 420.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody19.png',
                'category_id' => 2,
            ],
            [
                'name' => 'My Melody Flower Garland Dress Charm ',
                'price' => 470.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody20.png',
                'category_id' => 2,
            ],
            [
                'name' => 'My Melody Glitter Tea Party Figurine ',
                'price' => 690.0,
                'stock_qty' => 20,
                'image_url' => 'collection/mymelody/mymelody21.png',
                'category_id' => 2,
            ],


            // 🖤 Kuromi Collection
            [
                'name' => 'Kuromi Cupcake Celebration Figure',
                'price' => 490.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi2.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi Skull Hood Heart Figure',
                'price' => 430.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi3.png',
                'category_id' => 3,
            ],
             [
                'name' => 'Kuromi Gothic Frill Dress Figure',
                'price' => 670.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi4.png',
                'category_id' => 3,
            ],
             [
                'name' => 'Kuromi Best Friends Park Bench',
                'price' => 510.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi5.png',
                'category_id' => 3,
            ],
             [
                'name' => 'Kuromi Pastel Devil Angel Figure',
                'price' => 550.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi6.png',
                'category_id' => 3,
            ],
             [
                'name' => 'Kuromi Halloween Witch Ride Figurine',
                'price' => 690.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi7.png',
                'category_id' => 3,
            ],
             [
                'name' => 'Kuromi Brown Fur Flower Clip-On',
                'price' => 450.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi8.png',
                'category_id' => 3,
            ],
             [
                'name' => 'Kuromi Lavender Halloween Jester Plush',
                'price' => 620.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi9.png',
                'category_id' => 3,
            ],
             [
                'name' => 'Kuromi Black and Purple Gothic Clip',
                'price' => 480.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi10.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi Rose & Ribbon Dark Figure',
                'price' => 540.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi11.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi Royal Crown Key Figure',
                'price' => 620.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi12.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi Star Bow Lollipop Figure',
                'price' => 470.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi13.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi Striped Bow Winking Figure',
                'price' => 450.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi14.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi Purple Fluff Costume Plush',
                'price' => 680.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi15.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi Classic Pink Pedestal Figure',
                'price' => 400.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi16.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi School Uniform Plush',
                'price' => 550.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi17.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi Fluffy Lavender Frill Plush',
                'price' => 650.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi18.png',
                'category_id' => 3,
            ],
            [
                'name' => 'KuromiPolka Dot Tulle Dress Plush',
                'price' => 590.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi19.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi Red Lace Vampiress Plush',
                'price' => 530.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi20.png',
                'category_id' => 3,
            ],
            [
                'name' => 'Kuromi Potion Maker Figure',
                'price' => 690.0,
                'stock_qty' => 20,
                'image_url' => 'collection/kuromi/kuromi21.png',
                'category_id' => 3,
            ],


            // 🩵 Hirono Collection
            [
                'name' => 'Hirono Red Hoodie with Devil Cat',
                'price' => 450.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono2.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Plastic Bag Head Collector',
                'price' => 430.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono3.png',
                'category_id' => 4,
            ],
             [
                'name' => 'Hirono Little Prince Rose Figure',
                'price' => 590.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono4.png',
                'category_id' => 4,
            ],
             [
                'name' => 'Hirono The Other One Boxer',
                'price' => 480.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono5.png',
                'category_id' => 4,
            ],
             [
                'name' => 'Hirono The Distressed Pianist',
                'price' => 620.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono6.png',
                'category_id' => 4,
            ],
             [
                'name' => 'Hirono Bear Suit Explorer with Torch',
                'price' => 650.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono7.png',
                'category_id' => 4,
            ],
             [
                'name' => 'Hirono Crane Charm Chain Accessory',
                'price' => 520.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono8.png',
                'category_id' => 4,
            ],
             [
                'name' => 'Hirono Frog Backpack Clip-On',
                'price' => 490.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono9.png',
                'category_id' => 4,
            ],
             [
                'name' => 'Hirono Little Prince Flower Figure (Variant)',
                'price' => 550.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono10.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Creepy Bunny Suit Plushie',
                'price' => 680.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono11.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Sad Clown with Red Balloon',
                'price' => 450.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono12.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Melting Ghost Bath Figure',
                'price' => 430.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono13.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Puppet Master Figure',
                'price' => 660.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono14.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Cardboard King Figure',
                'price' => 590.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono15.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Book Stacker Scholar',
                'price' => 570.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono16.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Rose Flower Suit Figure',
                'price' => 610.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono17.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Monkey Business Phone Call',
                'price' => 690.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono18.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Winter Hat Dinosaur Friend',
                'price' => 400.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono19.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Scarecrow with Crow Figure',
                'price' => 540.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono20.png',
                'category_id' => 4,
            ],
            [
                'name' => 'Hirono Steampunk Space Pilot',
                'price' => 700.0,
                'stock_qty' => 20,
                'image_url' => 'collection/hirono/hirono21.png',
                'category_id' => 4,
            ],

            // 🌟 Twinkle Collection
            [
                'name' => 'Twinkle Chocolate Bear Bun Figure',
                'price' => 580.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle2.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Brown Fur Star Bag Charm',
                'price' => 480.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle3.png',
                'category_id' => 5,
            ],
             [
                'name' => 'Twinkle Big Hug Winter Figure',
                'price' => 540.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle4.png',
                'category_id' => 5,
            ],
             [
                'name' => 'Twinkle Lost and Broken Figure',
                'price' => 490.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle5.png',
                'category_id' => 5,
            ],
             [
                'name' => 'Twinkle Honey Bee My Honey Figurine',
                'price' => 560.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle6.png',
                'category_id' => 5,
            ],
             [
                'name' => 'Twinkle Star Light Night Lamp',
                'price' => 690.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle7.png',
                'category_id' => 5,
            ],
             [
                'name' => 'Twinkle Harlequin Jester Pin',
                'price' => 420.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle8.png',
                'category_id' => 5,
            ],
             [
                'name' => 'Twinkle Keep Shining Plush Charm',
                'price' => 400.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle9.png',
                'category_id' => 5,
            ],
             [
                'name' => 'Twinkle Dreamer Diorama Box',
                'price' => 700.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle10.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Fluffy Yellow Star Keychain',
                'price' => 450.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle11.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Black Pepper Sauce Dispenser',
                'price' => 510.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle12.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Blueberry Sauce Dispenser',
                'price' => 510.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle13.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Ketchup Sauce Dispenser',
                'price' => 510.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle14.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Alarm Clock Timekeeper Figure',
                'price' => 650.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle15.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Story Reader Plush Keychain',
                'price' => 430.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle16.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Sunny Flower Plush Keychain',
                'price' => 460.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle17.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Clock Face Plush Keychain',
                'price' => 490.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle18.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Sweet Dinosaur Plush Keychain',
                'price' => 450.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle19.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Pancake Boy Plush Keychain',
                'price' => 480.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle20.png',
                'category_id' => 5,
            ],
            [
                'name' => 'Twinkle Letter to My Star Figurine',
                'price' => 690.0,
                'stock_qty' => 20,
                'image_url' => 'collection/twinkle/twinkle21.png',
                'category_id' => 5,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}